### ISSUE TITLE
Where is the package util?

### ISSUE THREAD

**Issue by Alisaincd** [edilsonacjr/autoencoder#1]
Hi, I'm interested in your project. But when I tried to run it ,I got this error:"ImportError: No module named util". I noticed you import "loadsemeval2013" from package "util". So can you upload your module 'util' ?  So that I can learn the format of your input and run the file successfully eventually.
Best

**Comment by edilsonacjr** [comment]
Hi @Alisaincd, thanks for your interest. The loadsemeval2013 method just return a list of sentences/strings that is passed to all_sentences, so you don't need the util package, you just need to ensure that a list of sentences/strings is passed to all_sentences. I forgot to comment on that part of the code and remove the library. I hope it helped.
Regards

**Comment by Alisaincd** [comment]
Hi @ edilsonacjr, thank you very much! But I have one more question. If each item of all_sentence is a Chinese sentence, should I firstly cut the sentence to words? I mean ,the all_sentences should be like this"我  是  一个  男孩". Is it right?

**Comment by edilsonacjr** [comment]
That's right, you must separate each token/word by a space character, since I'm using Keras Tokenizer. But I think there is a Chinese Tokenizer for Keras that you could use if you want to.
